version: 2.1
commands:
  install-package-python:
    steps:
      - checkout
      - run: 
          command: |
            pip install pytest requests opencv-python pytest-html flask
  install-docker-compose:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: 'v2.17.3'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            sudo systemctl start docker


jobs:
  prepare-report-directory:
    docker:
      - image: cimg/python:3.7
    steps:
      - run:
          name: Report for Test
          command: |
            mkdir -p test-results


  test-create-project:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - install-package-python
      - run:
          name: Test Create Project
          command: |
            python -m pytest test_create_project.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

    

  start-container-and-test:
    docker:
      - image: cimg/node:20.1.0
    steps:
      - install-docker-compose
      - run:
          name: Start Container and Verify It's Working 
          command: |
              docker-compose down -v
              docker system prune -a
              sudo apt-get update
              set -x
              docker-compose up -d
              docker ps
      - run:
          name: Install Node
          command: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra
              newman run ./'Video Server API.postman_collection.json'
    

workflows:
  build-and-test-python:
    jobs:
      # - prepare-report-directory
      # - test-create-project:
      #     requires:
      #       - prepare-report-directory
      - start-container-and-test