version: 2.1
jobs:
  build-docker:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "!!!"
  build-docker-compose:
    - run:
      name: Install Docker Compose
      environment:
        COMPOSE_VERSION: v2.17.2
      command: |
        curl -SL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    - setup_remote_docker
      # - run:
      #     name: Nhân bản project
      #     command: |
      #       python -m pytest tests/api/test_create_project.py
      # - run:
      #     name: Test danh sách project
      #     command: |
      #       python -m pytest test_list_projects.py
      # - run:
      #     name: Test xóa project
      #     command: |
      #       python -m pytest test_delete_project.py
      # - run:
      #     name: Test truy xuất chi tiết project
      #     command: |
      #       python -m pytest test_retrieve_project_details.py
workflows:
  build-environment:
    jobs:
      - build-docker
      - build-docker-compose
  # test:
  #   jobs:
  #     - test-video-server-app