version: 2.1
orbs:
  newman: postman/newman@1.0.0
jobs:
  build-docker:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: 'v2.17.3'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
  start-container-and-test:
    docker:
      - image: cimg/base:2023.03
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start Container and Verify It's Working 
          command: |
              docker-compose down -v
              docker system prune -a
              sudo apt-get update
              set -x
              docker-compose up -d
              docker ps
      - newman/newman-run:
          collection: ./'Video Server API.postman_collection.json'
    

workflows:
  build-and-test:
    jobs:
      - build-docker
      - start-container-and-test:
          requires:
            - build-docker