version: 2.1

workflows:
  build-and-test:
    jobs:
      - build-docker
      # - start-container:
      #   requires:
      #     - build-docker

jobs:
  build-docker:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: 'v2.17.3'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

  start-container:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start Container and Verify It's Working 
          command: |
              set -x
              docker-compose up -d
              docker ps
