version: 2.1
jobs:
  build-docker:
    working_directory: /videoserver_group20
    docker:
      - image: cimg/base:2023.03
     steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
            
      # - run:
      #     name: Nhân bản project
      #     command: |
      #       python -m pytest tests/api/test_create_project.py
      # - run:
      #     name: Test danh sách project
      #     command: |
      #       python -m pytest test_list_projects.py
      # - run:
      #     name: Test xóa project
      #     command: |
      #       python -m pytest test_delete_project.py
      # - run:
      #     name: Test truy xuất chi tiết project
      #     command: |
      #       python -m pytest test_retrieve_project_details.py
workflows:
  build-environment:
    jobs:
      - build-docker
  # test:
  #   jobs:
  #     - test-video-server-app