version: 2.1

orbs:
  newman: postman/newman@1.0.0
  docker: circleci/docker@2.2.0
  python: circleci/python@1.0.0
jobs:
  build-docker:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - run: |
          docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
      - docker/check:
          docker-username: DOCKERHUB_LOGIN  # DOCKER_LOGIN is the default value, if it exists, it automatically would be used.
          docker-password: DOCKERHUB_PASSWORD  # DOCKER_PASSWORD is the default value
  build-python:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: git clone https://github.com/superdesk/video-server.git && pip install -e video-server/[dev] && pip install pytest requests flask pymongo /*
            
      # - run:
      #     name: Nhân bản project
      #     command: |
      #       python -m pytest tests/api/test_create_project.py
      # - run:
      #     name: Test danh sách project
      #     command: |
      #       python -m pytest test_list_projects.py
      # - run:
      #     name: Test xóa project
      #     command: |
      #       python -m pytest test_delete_project.py
      # - run:
      #     name: Test truy xuất chi tiết project
      #     command: |
      #       python -m pytest test_retrieve_project_details.py
workflows:
  build-environment:
    jobs:
      - build-docker
      - build-python
  # test:
  #   jobs:
  #     - test-video-server-app