version: 2.1

jobs:
  install-package-python:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: 
          command: |
            echo "!!!"
            pip install pytest requests opencv-python pytest-html 

  prepare-report-directory:
    docker:
      - image: cimg/python:3.7
    steps:
      - run:
          name: Chuẩn bị cho báo cáo test
          command: |
            mkdir -p test-results


  test-create-project:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          name: Test tạo project
          command: |
            python -m pytest test_create_project.py  -v -s --html=test-results/report.html
      - store_artifacts:
          path: test-results

  build-docker:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: 'v2.17.3'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
  start-container-and-test:
    docker:
      - image: cimg/node:20.1.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start Container and Verify It's Working 
          command: |
              docker-compose down -v
              docker system prune -a
              sudo apt-get update
              set -x
              docker-compose up -d
              docker ps
      - run:
          name: Install Node
          command: |
              npm install -g newman
              npm install -g newman-reporter-htmlextra
              newman run ./'Video Server API.postman_collection.json'
    

workflows:
  build-and-test-python:
    jobs:
      - install-package-python
      - prepare-report-directory:
          requires:
            - install-package-python
      - test-create-project:
          requires:
            - prepare-report-directory
      # - build-docker
      # - start-container-and-test:
      #     requires:
      #       - build-docker