name: Docker-Compose

on:
  push:
    branches: [ "datdnthcmute" ]
  pull_request:
    branches: [ "datdnthcmute" ]

permissions: read-all

jobs:
  docker-compose:
    name: Build-and-Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Start Containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Check Containers
      run: docker ps

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory for results
      run: mkdir -p testResults

    
    - name: Run POSTMAN collection
      run: |
        newman run VideoServerAPI.postman_collection.json --environment=VideoServerAPI.postman_environment.json --globals=workspace.postman_globals.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme
    
    - name: Output the run Test API
      uses: actions/upload-artifact@v3
      with:
        name: APITestReport
        path: testResults
