name: Docker-Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions: read-all

jobs:
  docker-compose:
    name: Start Docker Compose
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Start Containers
      run: docker-compose -f "docker-compose.yml" up -d --build

  check-container:
    name: Check Docker Container Started
    runs-on: ubuntu-latest

    steps:
    - name: Check Containers
      run: docker ps

